//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase.WebControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBase.WebControls.Resources.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CheckBox_False {
            get {
                return ResourceManager.GetString("CheckBox_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string CheckBox_True {
            get {
                return ResourceManager.GetString("CheckBox_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo inválido..
        /// </summary>
        internal static string Validator_Email {
            get {
                return ResourceManager.GetString("Validator_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato inválido..
        /// </summary>
        internal static string Validator_Format {
            get {
                return ResourceManager.GetString("Validator_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no es numérico..
        /// </summary>
        internal static string Validator_Format_Currency {
            get {
                return ResourceManager.GetString("Validator_Format_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no es una fecha válida..
        /// </summary>
        internal static string Validator_Format_Date {
            get {
                return ResourceManager.GetString("Validator_Format_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} es inválido. Asegúrese de ingresar un correo electrónico válido..
        /// </summary>
        internal static string Validator_Format_Email {
            get {
                return ResourceManager.GetString("Validator_Format_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no es un numero entero..
        /// </summary>
        internal static string Validator_Format_Integer {
            get {
                return ResourceManager.GetString("Validator_Format_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} está incompleto..
        /// </summary>
        internal static string Validator_Format_RequiredField {
            get {
                return ResourceManager.GetString("Validator_Format_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango inválido..
        /// </summary>
        internal static string Validator_Range {
            get {
                return ResourceManager.GetString("Validator_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerido..
        /// </summary>
        internal static string Validator_RequiredField {
            get {
                return ResourceManager.GetString("Validator_RequiredField", resourceCulture);
            }
        }
    }
}
